version: "3.9"
services:
    web:
        build: .
        container_name: albumcollection
        ports:
            - "8000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: sqlserver
        environment:
            SA_PASSWORD: "r22rbf8*PUHjqzb3"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433