version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "r22rbf8*PUHjqzb3"
            ACCEPT_EULA: "Y"
        ports:  
            - '1433:1433'  
        expose:  
            - 1433